### ISSUE TITLE
Cant Save Images

### ISSUE THREAD

**Issue by MordragT** [Zylann/godot_channel_packer_plugin#2]
When pressing Save Output the Window just closes.

**Comment by Zylann** [comment]
There is a UI problem in Godot 3 which causes my layout to be destroyed: https://github.com/godotengine/godot/issues/17626

As a result the buttons may indeed be inoperant. I think you can workaround this by clicking on the part of the button which lies above the window background. tbh I'd like this to be fixed somehow in the engine... I should take a look how it behaves in 3.1.

In the meantime, enlarging the window might help.

**Comment by Zylann** [comment]
Tested in 3.1, it still happens, but I found why, see https://github.com/Zylann/godot_channel_packer_plugin/issues/1

**Comment by Zylann** [comment]
Should be fixed by 65f60f3e58bc5613633cdd316c8dd018ec975bc2

**Comment by MordragT** [comment]
Yep great thanks for the fix.
